pipeline {
    agent any
    tools {
        nodejs 'nodejs'
    }
    stages {
        stage("Build frontend") {
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/EliasZunigaUSACH/Tingeso2025_1']])
					dir("payroll-frontend"){
                		bat 'npm install'
                        bat 'npm run build'
					}
            }
        }

        stage('Build and Push Docker Image'){
            steps{
				dir("payroll-frontend"){
	                script{
						withDockerRegistry(credentialsId: 'docker-credentials'){
	                    	bat 'docker build -t eliaszngusach/payroll-frontend:latest .'
							bat 'docker push eliaszngusach/payroll-frontend:latest'
						}
	                }
				}
            }
        }
    }
}
