pipeline {
    agent any
    tools {
        nodejs 'nodejs'
    }
    stages {
        stage("Build frontend") {
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/EliasZunigaUSACH/Tingeso2025_1']])
					dir("payroll-frontend"){
                		bat 'npm install'
                        bat 'npm run build'
					}
            }
        }

        stage('Build docker image'){
            steps{
                script{
                    bat 'docker build -t eliaszngusach/payroll-frontend:latest .'
                }
            }
        }
        stage('Push image to Docker Hub'){
            steps{
                script{
                   withCredentials([string(credentialsId: 'docker-credentials')])
                   bat 'docker push eliaszngusach/payroll-frontend:latest'
                }
            }
        }
    }
}
