pipeline {
    agent any
    tools {
        nodejs 'nodejs'
    }
    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage('Install npm dependencies') {
            steps {
                bat 'npm install'
            }
        }

        stage('Run npm build') {
            steps {
                bat 'npm run build'
            }
        }

        stage('Build docker image'){
            steps{
                script{
                    bat 'docker build -t eliaszngusach/payroll-frontend:latest .'
                }
            }
        }
        stage('Push image to Docker Hub'){
            steps{
                script{
                   withCredentials([string(credentialsId: 'docker-credentials')])
                   bat 'docker push eliaszngusach/payroll-frontend:latest'
                }
            }
        }
    }
}
